### ISSUE TITLE
Should we implement camera motion control?

### ISSUE THREAD

**Issue by aronson** [emanguy/RoboticsImageProcessor#3]
This is an extension of the conversation at 582bedb853cdb46c3e4a3420e85298d6133967db and f86439ce8280aa5571ae20495c7b777616153455

I think we should use network traffic to ask the cRIO to move the servos mounted on the motor.

I don't think network traffic is an issue as we have a 100 mb/s backbone between the camera, cRIO, and R-PI. None of the traffic should enter onto the field, since we do not communicate outside of the robot's Ethernet backbone.

**Comment by emanguy** [comment]
I'm sharing this with Al to get his input. I'm against it because I feel the implementation could end badly, especially considering all the issues we had with the potentiometer last year with the lazy Susan rotation system on our turret.

**Comment by aronson** [comment]
To add some of my personal experience: the last team I was on had a camera that was mounted on a little metal frame with two servos that adjusted the X and Y rotation with a 180 degree range.

We're not doing inaccurate math using a potentiometer, we're literally sending commands like `setServo(Y, 90)` to face straight forward, or `setServo(X, 180)` to look straight up (assume the method is `setServo( int axis, double angle )`) The angle is very precise and would just introduce one more angle to multiply by when doing the homological transformation.

However, this is obviously not a priority and the level of work needed to add this kind of system is very low compared to the work we need to do getting the homological transform and pose done. This is an issue we can solve in person with the mentors later. :smile_cat:
