### ISSUE TITLE
Current luminance filter is slow

### ISSUE THREAD

**Issue by aronson** [emanguy/RoboticsImageProcessor#4]
We could probably speed up the luminance to bit matrix conversion (that's what `luminanceChart` becomes) using the [Threshold](http://docs.opencv.org/doc/tutorials/imgproc/threshold/threshold.html) functions.

Once we're running on the Pi in real time, every optimization helps.

**Comment by emanguy** [comment]
I can take care of this tomorrow, no problem.

**Comment by aronson** [comment]
I'm working on it now, but if I can't get something fully working you should jump on in

**Comment by aronson** [comment]
Fixed in 8db99e1ed1cd7512593b23557a12f7e8508aeb4a
